# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(verbose_name='start_time')),
                ('end_time', models.IntegerField(blank=True, null=True, verbose_name='end_time')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_measure', models.IntegerField(verbose_name='similarity_measure')),
                ('other_sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation-app.Annotation')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotationsimilarity_related', to='annotation-app.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('is_reference', models.BooleanField(default=False)),
                ('has_annotations', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='annotation-app.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tiers', to='annotation-app.Tier')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='tiers',
            field=models.ManyToManyField(blank=True, to='annotation-app.Tier'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation-app.Sound'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation-app.Tier'),
        ),
    ]
