# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation-app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='waveform_data',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
