# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation-app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='reference_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_related', to='annotation-app.Sound'),
        ),
    ]
