# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation-app', '0002_sound_waveform_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='tier',
            new_name='exercise',
        ),
    ]
