# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation-app', '0002_exercise_reference_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tiers',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='annotation-app.Tier'),
        ),
    ]
