# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation-app', '0003_auto_20161026_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier',
            old_name='exercise',
            new_name='tier',
        ),
    ]
