# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.IntegerField(verbose_name=b'start_time')),
                ('end_time', models.IntegerField(blank=True, null=True, verbose_name=b'end_time')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_measure', models.IntegerField(verbose_name=b'similarity_measure')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotationsimilarity_related', to='annotationapp.Annotation')),
                ('similar_sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationapp.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('waveform_data', models.CharField(max_length=200)),
                ('is_reference', models.BooleanField(default=False)),
                ('has_annotations', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sounds', to='annotationapp.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='annotationapp.Exercise')),
                ('parent_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tiers', to='annotationapp.Tier')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='reference_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_related', to='annotationapp.Sound'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotationapp.Sound'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotationapp.Tier'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
