# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='reference_pitch_sound',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='end_time',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='start_time',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
