# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='original_filename',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
