# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reference_pitch_sound',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
