# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 10:23
from __future__ import unicode_literals

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_auto_20161117_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reference_pitch_sound',
            field=models.FileField(blank=True, null=True, upload_to=annotation.models.exercise_upload_to),
        ),
    ]
