# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_sound_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tiers',
            field=models.ManyToManyField(to='annotation.Tier'),
        ),
    ]
