# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20161128_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='waveform_data',
        ),
    ]
