# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0003_tag_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationsimilarity',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='similarity_measures', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
