# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20161128_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='data_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='annotation.DataSet'),
            preserve_default=False,
        ),
    ]
