# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_annotationsimilarity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
