# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_remove_sound_waveform_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
    ]
