# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_exercise_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='annotation_state',
            field=models.CharField(choices=[('E', 'empty'), ('I', 'incomplete'), ('C', 'complete')], default='E', max_length=2),
        ),
    ]
