# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_dataset_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(choices=[('S', 'segment'), ('U', 'upbeat'), ('D', 'downbeat')], default='S', max_length=2),
        ),
    ]
