# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0012_tier_special_parent_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='point_annotations',
            field=models.BooleanField(default=False),
        ),
    ]
