# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_tier_similarity_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
