# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0017_tier_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
