# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0018_sound_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationsimilarity',
            name='similar_sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='annotation.Annotation'),
        ),
    ]
