# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0019_auto_20171009_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationsimilarity',
            name='similar_sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Annotation'),
        ),
    ]
