# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0020_auto_20171009_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
