# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0021_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete', to='annotation.Sound'),
        ),
    ]
