"""
Django settings for Annotation project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n*0*g*65p%@be0@(qh1j3gq!&z+hrxb5wbkax8-f+s^(hob=54'


# Application definition

INSTALLED_APPS = [
    'annotation.apps.AnnotationToolConfig',
    'accounts.apps.AccountsConfig',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'raven.contrib.django.raven_compat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'simannotator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simannotator.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_URL = "/media/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(os.path.dirname(__file__), 'static'),
]

STATIC_URL = '/static/'

deploy_env = os.environ.get('DEPLOY_ENV')
allowed_host = os.environ.get('DJANGO_ALLOWED_HOST')
raven_dsn = os.environ.get('SIM_RAVEN_DSN')
import dj_database_url
if deploy_env == 'prod':
    debug = False
    ALLOWED_HOSTS = ['localhost', 'asplab-web1', 'asplab-web1.s.upf.edu', 'simannotator.mtg.upf.edu']
    if allowed_host:
        ALLOWED_HOSTS.append(allowed_host)

    RAVEN_CONFIG = {
        'dsn': raven_dsn,
    }

else:
    debug = True
    ALLOWED_HOSTS = ['simannotator-test.mtg.upf.edu']

default_url = 'postgres://postgres@db/postgres'
DATABASE_URL_ENV_NAME = 'DATABASE_URL'

DEBUG = debug
DATABASES = {'default': dj_database_url.config(DATABASE_URL_ENV_NAME, default=default_url)}

MEDIA_ROOT = "/media"
TEMP_ROOT = "/tmp"

STATIC_ROOT = "/static"

EXPORT_PATH = "/export"
IMPORT_PATH = "/import"

# in case some development settings are used
if os.path.isfile(os.path.join(os.getcwd(), 'simannotator/development_settings.py')):
    from .development_settings import *
