# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='related_tiers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Tier'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tiers',
            field=models.ManyToManyField(blank=True, null=True, to='annotation_tool.Tier'),
        ),
    ]
