# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0003_dataset_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(verbose_name='start_time')),
                ('end_time', models.IntegerField(blank=True, null=True, verbose_name='end_time')),
                ('related_annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation_tool.Annotation')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation_tool.Sound')),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tiers',
            field=models.ManyToManyField(blank=True, to='annotation_tool.Tier'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
