# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_tool', '0004_auto_20161018_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='has_annotations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sound',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
